### ISSUE TITLE
Migrate to Nextclade v3

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/mpox#280]
[Migration to Nextclade v3 guide](https://docs.nextstrain.org/projects/nextclade/en/stable/user/migration-v3.html) for reference.

Phylogenetic workflow was migrated in https://github.com/nextstrain/mpox/pull/245. 

## TODOs

- [x] update nextclade2 commands in [ingest rules](https://github.com/nextstrain/mpox/blob/b453693963b4eed7ab0937246b0bc2d18e49aa7c/ingest/rules/nextclade.smk)
- [x] update files uploaded to S3 in [ingest/nextstrain_automation](https://github.com/nextstrain/mpox/blob/b453693963b4eed7ab0937246b0bc2d18e49aa7c/ingest/build-configs/nextstrain-automation/config.yaml#L21-L23)
- [x] Remove [reference to nextalign](https://github.com/nextstrain/mpox/blob/b453693963b4eed7ab0937246b0bc2d18e49aa7c/phylogenetic/defaults/description.md?plain=1#L15) in phylogenetic/defaults/description.md
- [x] Update [files linked](https://github.com/nextstrain/mpox/blob/b453693963b4eed7ab0937246b0bc2d18e49aa7c/phylogenetic/defaults/description.md?plain=1#L29-L32) in phylogenetic/defaults/description.md

**Comment by joverlee521** [comment]
Tracked down why we are currently using both MPXV and hMPXV Nextclade datasets in https://github.com/nextstrain/mpox/pull/114#discussion_r958185115:

> align now uses hmpxv. shouldn't matter much in practice, but I think people will be more confidence when the alignment is based on an actual sequence, rather than a reconstructed ancestor.

Since the v3 Nextclade datasets for [MPXV](https://github.com/nextstrain/nextclade_data/tree/master/data/nextstrain/mpox/all-clades#reference-sequence-and-reference-tree) and [hMPXV](https://github.com/nextstrain/nextclade_data/blob/master/data/nextstrain/mpox/clade-iib/README.md#reference-sequence-and-reference-tree) both use NC_063383.1 as the reference, we can just run Nextclade once using the MPXV dataset.
